// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";
import type { PageAst } from "./PageAst";

export type Ast = { "kind": "markdown", "root": Node } | { "kind": "open_api", "root": PageAst };