// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttributeValue } from "./AttributeValue";

export interface Attribute { key: string, value: AttributeValue | null, }