// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Height } from "./Height";
import type { MaxWidth } from "./MaxWidth";

export interface Box { padding: number, max_width: MaxWidth, class: string, height: Height, }