// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Build { id: number, inserted_at: string, git_branch: string, git_sha: string, manual_version_id: number | null, }