// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Build } from "./Build";
import type { CurrentPage } from "./CurrentPage";
import type { DebugInfo } from "./DebugInfo";
import type { DoctaveError } from "./DoctaveError";
import type { Project } from "./Project";
import type { Settings } from "./Settings";
import type { ViewMode } from "./ViewMode";

export type ContentApiResponse = { "kind": "content", page: CurrentPage, project: Project, build: Build, view_mode: ViewMode, sign_assets: boolean, debug_info: DebugInfo, } | { "kind": "site_asleep", http_status: number, message: string, is_owner: boolean, view_mode: ViewMode, } | { "kind": "password_auth_required", http_status: number, auth_url: string, view_mode: ViewMode, settings: Settings, version_name: string, message: string, sign_assets: boolean, } | { "kind": "private_site", http_status: number, message: string, view_mode: ViewMode, } | { "kind": "build_not_found", http_status: number, message: string, view_mode: ViewMode, } | { "kind": "build_pending", http_status: number, message: string, view_mode: ViewMode, } | { "kind": "invalid_project", http_status: number, message: string, errors: Array<DoctaveError>, view_mode: ViewMode, } | { "kind": "unknown_error", http_status: number, message: string, view_mode: ViewMode, };