// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ast } from "./Ast";
import type { Breadcrumb } from "./Breadcrumb";
import type { DoctaveError } from "./DoctaveError";
import type { OnThisPageHeading } from "./OnThisPageHeading";
import type { PageOptions } from "./PageOptions";

export type CurrentPage = { "status": "ok", http_status: number, ast: Ast, title: string | null, description: string, page_kind: string, breadcrumbs: Array<Breadcrumb>, on_this_page_headings: Array<OnThisPageHeading>, page_options: PageOptions, } | { "status": "error", http_status: number, errors: Array<DoctaveError>, page_options: PageOptions, page_kind: string, title: string, description: string, } | { "status": "not_found", http_status: number, page_options: PageOptions, };