// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoctaveError } from "./DoctaveError";
import type { NavSection } from "./NavSection";

export type CurrentNavigation = { "status": "ok", sections: Array<NavSection>, } | { "status": "error", errors: Array<DoctaveError>, };