// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugInfoStep } from "./DebugInfoStep";

export interface DebugInfo { performance: Array<DebugInfoStep> | null, }