// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

export interface DoctaveError { code: number, message: string, description: string, file: string | null, position: Position | null, }