// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";

export interface ExampleAst { name: string, summary: string | null, description_ast: Node | null, identifier: string, value: string, rendered_value: string | null, group_name: string, language: string | null, }