// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlexAlign } from "./FlexAlign";
import type { FlexDirection } from "./FlexDirection";
import type { FlexHeight } from "./FlexHeight";
import type { FlexJustify } from "./FlexJustify";
import type { FlexWrap } from "./FlexWrap";

export interface Flex { align: FlexAlign, padding: number, direction: FlexDirection, justify: FlexJustify, gap: number, wrap: FlexWrap, height: FlexHeight, class: string, }