// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeaderLink } from "./HeaderLink";

export interface Footer { links: Array<HeaderLink>, linkedin?: string, twitter?: string, github?: string, facebook?: string, discord?: string, }