// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalLink } from "./ExternalLink";
import type { InternalLink } from "./InternalLink";

export type HeaderLink = InternalLink | ExternalLink;