// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeaderLink } from "./HeaderLink";

export interface HeaderSettings { links: Array<HeaderLink>, cta: HeaderLink | null, }