// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviconIcon } from "./DeviconIcon";
import type { LucideIcon } from "./LucideIcon";
import type { UnknownIcon } from "./UnknownIcon";

export type Icon = { "set": "lucide" } & LucideIcon | { "set": "devicon" } & DeviconIcon | { "set": "unknown" } & UnknownIcon;