// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Integrations { hubspot_tracking_code?: string, ms_clarity_code?: string, ga_tracking_code?: string, plausible_tracking?: boolean, intercom_app_id?: string, statuspage_id?: string, }