// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExampleAst } from "./ExampleAst";
import type { SchemaAst } from "./SchemaAst";

export interface MediaTypeAst { name: string, schemas: Array<SchemaAst>, examples: Array<ExampleAst>, }