// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Metadata { field_name: string | null, component_name: string | null, recursive: boolean | null, title: string | null, }