// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMethod } from "./HttpMethod";

export type NavItem = { "kind": "subheading", label: string, collapsed?: boolean, collapsible?: boolean, items?: Array<NavItem>, } | { "kind": "link", label: string, external_href?: string, href?: string, title?: string, collapsed?: boolean, collapsible?: boolean, http_method?: HttpMethod, items?: Array<NavItem>, };