// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavItem } from "./NavItem";

export interface NavSection { heading: string | null, collapsed: boolean, collapsible: boolean, items: Array<NavItem>, }