// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExampleAst } from "./ExampleAst";
import type { Node } from "./Node";
import type { ParameterAst } from "./ParameterAst";
import type { RequestBodyAst } from "./RequestBodyAst";
import type { SecurityRequirementAst } from "./SecurityRequirementAst";
import type { StatusAst } from "./StatusAst";

export interface OperationAst { summary: string | null, description_ast: Node | null, method: string, anchor_tag: string, route_pattern: string, server_route_patterns: Array<string>, header_params: Array<ParameterAst>, query_params: Array<ParameterAst>, path_params: Array<ParameterAst>, cookie_params: Array<ParameterAst>, request_body?: RequestBodyAst, responses: Array<StatusAst>, security_requirements: Array<SecurityRequirementAst>, request_examples: Array<ExampleAst>, }