// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationAst } from "./OperationAst";
import type { Tag } from "./Tag";

export interface PageAst { tag: Tag, operations: Array<OperationAst>, download_url: string | null, }