// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageWidth } from "./PageWidth";

export interface PageOptions { hide_navigation: boolean, hide_side_table_of_contents: boolean, page_width: PageWidth, breadcrumbs: boolean, hidden_from_search: boolean, }