// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";
import type { SchemaAst } from "./SchemaAst";

export interface ParameterAst { schema: SchemaAst | null, description_ast: Node | null, }