// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentNavigation } from "./CurrentNavigation";
import type { Settings } from "./Settings";
import type { Site } from "./Site";
import type { Tab } from "./Tab";
import type { Version } from "./Version";

export interface Project { site: Site, active_version: Version | null, settings: Settings, tabs: Array<Tab>, active_tab_index: Array<number>, active_navigation: CurrentNavigation, custom_css: Array<string>, favicon_url: string | null, }