// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaTypeAst } from "./MediaTypeAst";
import type { Node } from "./Node";

export interface RequestBodyAst { description_ast: Node | null, media_types: Array<MediaTypeAst>, }