// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Build } from "./Build";
import type { DebugInfo } from "./DebugInfo";
import type { RenderOptions } from "./RenderOptions";
import type { Site } from "./Site";
import type { Version } from "./Version";
import type { ViewMode } from "./ViewMode";

export interface ResponseContext { options: RenderOptions, site: Site, custom_css: Array<string>, favicon_url: string | null, active_version: Version | null, build: Build, view_mode: ViewMode, sign_assets: boolean, debug_info: DebugInfo, }