// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "./Metadata";
import type { Node } from "./Node";

export interface SchemaAst { schemas: Array<SchemaAst>, required?: boolean, description_ast?: Node, title?: string, type_name: string, format?: string, pattern?: string, default?: string, deprecated: boolean, minimum?: string, maximum?: string, multiple_of?: string, min_length?: number, max_length?: number, enumeration: Array<string | null> | null, example_string?: string, combination_explanation?: string, media_type?: string, metadata?: Metadata, expanded: boolean, }