// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";
import type { OAuth2FlowAst } from "./OAuth2FlowAst";

export type SecurityRequirementAst = { "kind": "http", "data": { name: string, description_ast: Node | null, scheme: string, bearer_format: string | null, } } | { "kind": "api_key", "data": { name: string, description_ast: Node | null, key_name: string, key_location: string, } } | { "kind": "o_auth2", "data": { name: string, description_ast: Node | null, all_scopes: Array<[string, string]>, required_scopes: Array<string>, flows: Array<OAuth2FlowAst>, } } | { "kind": "open_id", "data": { name: string, description_ast: Node | null, open_id_connect_url: string, } };