// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Footer } from "./Footer";
import type { HeaderSettings } from "./HeaderSettings";
import type { OpenApi } from "./OpenApi";
import type { Redirect } from "./Redirect";
import type { TabDescription } from "./TabDescription";
import type { Theme } from "./Theme";
import type { UserPreference } from "./UserPreference";
import type { ValeSettings } from "./ValeSettings";

export interface SettingsV2 { title: string, header?: HeaderSettings, theme: Theme, open_api: Array<OpenApi>, styles: Array<string>, redirects: Array<Redirect>, user_preferences: Record<string, UserPreference>, tab_descriptions: Array<TabDescription>, footer: Footer, vale: ValeSettings | null, }