// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsV1 } from "./SettingsV1";
import type { SettingsV2 } from "./SettingsV2";

export type Settings = { "version": "2" } & SettingsV2 | { "version": "1" } & SettingsV1;