// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorMode } from "./ColorMode";
import type { Colors } from "./Colors";
import type { Favicon } from "./Favicon";
import type { HeaderSettings } from "./HeaderSettings";
import type { Logo } from "./Logo";
import type { OpenApi } from "./OpenApi";
import type { Redirect } from "./Redirect";
import type { UserPreference } from "./UserPreference";

export interface SettingsV1 { color_mode: ColorMode, colors: Colors, header?: HeaderSettings, title: string, open_api: Array<OpenApi>, user_preferences: Record<string, UserPreference>, logo?: Logo, favicon?: Favicon, styles: Array<string>, redirects: Array<Redirect>, }