// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Integrations } from "./Integrations";
import type { Version } from "./Version";

export interface Site { id: number, team_id: number, slug: string, versions: Array<Version>, integrations: Integrations, collecting_feedback: boolean, canonical_domain: string, }