// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeaderAst } from "./HeaderAst";
import type { MediaTypeAst } from "./MediaTypeAst";
import type { Node } from "./Node";

export interface StatusAst { code: string, media_types: Array<MediaTypeAst>, description_ast: Node, headers: Array<HeaderAst>, }