// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Icon } from "./Icon";

export interface SubTab { label: string, path: string, href: string, icon: Icon | null, }