// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IconDescription } from "./IconDescription";

export interface SubTabDescription { path: string | null, external: string | null, label: string, icon: IconDescription | null, }