// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabV1 } from "./TabV1";
import type { TabV2 } from "./TabV2";

export type Tab = { "version": "1" } & TabV1 | { "version": "2" } & TabV2;