// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IconDescription } from "./IconDescription";
import type { SubTabDescription } from "./SubTabDescription";

export interface TabDescription { path: string | null, external: string | null, label: string, subtabs: Array<SubTabDescription>, icon: IconDescription | null, }