// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Icon } from "./Icon";

export interface TabV2 { label: string, subtabs: Array<TabV2>, href: string, is_external: boolean, icon: Icon | null, }