// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Icon } from "./Icon";
import type { SubTab } from "./SubTab";

export interface TabV1 { label: string, subtabs: Array<SubTab>, href: string, external_href: string | null, icon: Icon | null, }