// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorMode } from "./ColorMode";
import type { ColorsV2 } from "./ColorsV2";
import type { Favicon } from "./Favicon";
import type { Logo } from "./Logo";
import type { Radius } from "./Radius";

export interface Theme { name: "Theme", color_mode: ColorMode, colors: ColorsV2, logo: Logo | null, radius: Radius, favicon: Favicon | null, }