// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserPreferenceOption } from "./UserPreferenceOption";

export interface UserPreference { label: string, default: string, values: Array<UserPreferenceOption>, }