// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ValeSettings { version: string | null, config_file_path: string | null, }