// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VersionVisibility } from "./VersionVisibility";

export interface Version { id: number, label: string, href: string, visibility: VersionVisibility, default: boolean, }