[package]
name = "colorstuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
macroquad = "0.4.2"
palette = "0.7.3"
libdoctave = { path = "../.." }
cargo-watch = "8.5.2"
