name: Format

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          node-version: 24
      - run: cargo fmt --all -- --check

      - uses: actions/setup-node@v5
      - run: npm install
      - run: npm run format:check
