name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/_job-build.yaml
  test:
    uses: ./.github/workflows/_job-test.yaml
  format:
    uses: ./.github/workflows/_job-format.yaml
