name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build:
    uses: ./.github/workflows/jobs/build-docs.yaml
  deploy:
    needs: build
    uses: ./.github/workflows/jobs/deploy-pages.yaml
