name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_job-build-docs.yaml
  deploy:
    needs: build
    uses: ./.github/workflows/_job-deploy-pages.yaml
