name: On push

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  test:
    uses: ./.github/workflows/test.yaml
  format:
    uses: ./.github/workflows/format.yaml
